# Generated by Django 5.2.7 on 2026-01-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
    ]
